### ISSUE TITLE
how to get the sem version from an array of versions

### ISSUE THREAD

**Issue by dengyaolong** [sindresorhus/latest-semver#1]
Input: a semver string, array of versions
Output: the version in versions which is valid of the semver string.

Like: semver=`^1.2.1`.  versions=`['1.2.0', '1.2.1', '1.3.1']`
return 1.3.1?

**Comment by sindresorhus** [comment]
That's out of scope for this module. See `maxSatisfying` in https://github.com/npm/node-semver
